# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SPH_Mobile_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SPH_Mobile_App
  pod 'CardViewList', '~> 1.1.8'


  target 'SPH_Mobile_AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
